import React, { createContext, useContext, useState } from 'react';
import { trackLanguageChange } from '@/components/Analytics';

type Language = 'nl' | 'ro';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

const translations = {
  nl: {
    // Navigation
    'nav.home': 'Home',
    'nav.about': 'Over Ons',
    'nav.products': 'Producten',
    'nav.catering': 'Traiteur',
    'nav.order': 'Bestel Online',
    'nav.contact': 'Contact',
    
    // Home Page
    'home.hero.title': 'Uw Kwaliteitsslager in Zwevezele',
    'home.hero.subtitle': 'Traditioneel ambacht\nmet moderne service',
    'home.hero.cta': 'Bestel Nu Online',
    'home.features.online.title': 'Online Bestellen',
    'home.features.online.desc': 'Bestel gemakkelijk online en haal op wanneer het u uitkomt',
    'home.features.quality.title': 'Premium Kwaliteit',
    'home.features.quality.desc': 'Enkel het beste vlees van vertrouwde lokale leveranciers',
    'home.features.fresh.title': 'Verse Bereiding',
    'home.features.fresh.desc': 'Dagelijks vers bereid volgens traditionele recepten',
    'home.specials.title': 'Deze Week in de Aanbieding',
    'home.specials.promo.title': 'Promo 21 & 22 November',
    'home.specials.promo.offer1': 'Kopen van minimum €30 → Gratis 200 gr Préparé van de Chef',
    'home.specials.promo.offer2': 'Kopen van €50 → Gratis 500 gr gehakt',
    'home.specials.order': 'Bestel Nu',
    'home.cta.title': 'Klaar om te Bestellen?',
    'home.cta.subtitle': 'Ontdek ons volledig assortiment en bestel vandaag nog voor afhaling',
    'home.cta.orderBtn': 'Online Bestellen',
    'home.cta.productsBtn': 'Bekijk Producten',
    
    // About Page
    'about.title': 'Over Slagerij John',
    'about.subtitle': 'De nieuwste culinaire aanwinst in Zwevezele',
    'about.tagline': 'Ontdek de échte smaak van vers vlees! In onze slagerij vind je alleen vers vlees, ambachtelijke bereidingen en specialiteiten die met zorg en passie worden gemaakt. We doen alles met liefde, zodat jij elke dag kunt genieten van een authentieke smaak.',
    'about.story.title': 'Ons Verhaal',
    'about.story.p1': 'Welkom bij Slagerij John, de nieuwste culinaire aanwinst in Zwevezele! In de Bruggestraat 146A, waar vroeger bakkerij Choc-O-Fee en bakkerij Geert gevestigd waren, hebben Ion (John) Nistor (36) en zijn echtgenote Georgiana (31) hun droom waargemaakt met de opening van hun eigen slagerij.',
    'about.story.p2': '"Eigenlijk heet ik Ion, maar iedereen noemt me John," legt de slager uit. "Ion is de Roemeense versie van die naam en toen we destijds naar België kwamen werd ik in de omgang heel snel John genoemd. Die naam is blijven plakken. Zelfs mijn vrouw noemt me zo!"',
    'about.values.experience.title': 'Ervaring & Passie',
    'about.values.experience.desc': 'Al op 16-jarige leeftijd begon John zijn carrière in Roemenië, waar hij ervaring opdeed in slagerijen en slachthuizen.',
    'about.values.culture.title': 'Twee Culturen',
    'about.values.culture.desc': 'Een unieke mix van Belgische en Roemeense specialiteiten, symbolisch vertegenwoordigd door onze ballonfiguren in beide nationale kleuren.',
    'about.values.local.title': 'Lokale Verbondenheid',
    'about.values.local.desc': 'Al 8 jaar thuis in Zwevezele, waar het gezin met drie kinderen in de Laurierstraat woont en volledig ingeburgerd is.',
    'about.specialties.title': 'Onze Specialiteiten',
    'about.specialties.intro': 'In onze toonbank vindt u een breed assortiment aan:',
    'about.specialties.item1': 'Klassieke Belgische vleeswaren en charcuterie',
    'about.specialties.item2': 'Traditionele bereide gerechten zoals stoofvlees en vol-au-vent',
    'about.specialties.item3': 'Roemeense specialiteiten zoals \'Mici\' (gekruide rundergehaktrolletjes)',
    'about.specialties.item4': 'Verse belegde broodjes',
    'about.specialties.item5': 'Huisgemaakte worsten van varkens- en rundsgrehakt',
    'about.team.title': 'Het Team achter Slagerij John',
    'about.team.names': 'Georgiana Nistor & Ion (John) Nistor',
    'about.team.role': 'Eigenaars',
    'about.team.desc': 'Ion (John) en Georgiana staan klaar om u te helpen met advies, speciale wensen of simpelweg een praatje. Met hun passie voor kwaliteitsvlees en persoonlijke service delen ze graag hun kennis over de beste bereidingswijzen en recepten. Kom gerust langs en maak kennis!',
    'about.gallery.title': 'Onze Slagerij',
    
    // Catering Page
    'catering.title': 'Traiteur',
    'catering.subtitle': 'De Authentieke Barbecue-ervaring, direct op jouw evenement',
    'catering.p1': 'Of je nu een intiem feest met vrienden organiseert of een grote buurtviering, ons team transformeert jouw evenement in een culinair genot. Wij nemen alles wat met het barbecuestation te maken heeft uit handen, zodat jij tijd hebt voor je gasten.',
    'catering.p2': 'Ons pakket omvat:\n\nCompleet menu: Een gevarieerde selectie van voorgerechten en barbecuegerechten, ter plaatse bereid op onze professionele mobiele units.\n\nDranken: Diverse assortimenten om de maaltijd aan te vullen.',
    'catering.p3': 'Logistiek inbegrepen: We zorgen voor het nodige bestek en borden.',
    'catering.p4': 'Flexibiliteit: We bieden volledige service op locatie (koken en serveren bij de barbecue) of de optie om het eten af te halen. Jij kiest, wij zorgen voor het vuur!',
    'catering.gallery.title': 'Onze Traiteurservice',
    
    // Products Page
    'products.title': 'Ons Assortiment',
    'products.hero.title': 'Ons Assortiment',
    'products.hero.subtitle': 'Ontdek ons uitgebreide en ambachtelijke assortiment van topkwaliteit vlees, dagelijks vers voor u bereid.',
    'products.beef.title': 'Rundvlees: Passie voor Kwaliteit',
    'products.beef.subtitle': 'Ontdek ons zorgvuldig geselecteerde rundvlees, bekend om zijn malsheid en rijke smaak. Perfect voor elke gelegenheid, van een snelle maaltijd tot een feestelijk diner.',
    'products.beef.item1': 'Biefstukken: Sappig en mals, van klassieke Hollandse biefstuk tot premium ribeye',
    'products.beef.item2': 'Rosbief: Heerlijk uit de oven, perfect voor een speciale maaltijd',
    'products.beef.item3': 'Gehakt (Rund): Puur en smaakvol, ideaal voor burgers, sauzen en ovenschotels',
    'products.beef.item4': 'Stoofvlees: Langzaam gegaard voor een onvergetelijke, diepe smaak',
    'products.beef.item5': 'Riblappen: Perfect voor de BBQ of een krachtige stoofpot',
    'products.beef.item6': 'Ossenhaas: Het meest malse stukje rundvlees, voor een onvergetelijke ervaring',
    'products.beef.cta': 'Bestel Online',
    'products.pork.title': 'Varkensvlees: Ambachtelijk en Smaakvol',
    'products.pork.subtitle': 'Van traditionele bereidingen tot moderne delicatessen, ons varkensvlees staat garant voor kwaliteit en smaak.',
    'products.pork.item1': 'Varkenshaas: Mals en veelzijdig, ideaal voor diverse gerechten',
    'products.pork.item2': 'Koteletten: Sappige koteletten voor op de grill of in de pan',
    'products.pork.item3': 'Gehakt (Varken): Vers gedraaid, perfect voor smakelijke balletjes of een vulling',
    'products.pork.item4': 'Speklappen: Krokant gebakken, een ware traktatie',
    'products.pork.item5': 'Braadworst: Onze eigen receptuur, heerlijk vol van smaak',
    'products.pork.item6': 'Huisgemaakte Worst: Ontdek onze unieke, dagelijks vers gemaakte worsten',
    'products.pork.cta': 'Bestel Online',
    'products.poultry.title': 'Gevogelte: Vers en Licht',
    'products.poultry.subtitle': 'Geniet van onze dagverse kip, kalkoen en gevogelte specialiteiten. Licht, smaakvol en veelzijdig.',
    'products.poultry.item1': 'Hele Kip: Perfect voor braden of grillen, vol van smaak',
    'products.poultry.item2': 'Kipfilet: Mals en mager, veelzijdig in elk gerecht',
    'products.poultry.item3': 'Kippendijen: Sappiger dan filet, ideaal voor stoofschotels of curry',
    'products.poultry.item4': 'Kalkoenfilet: Een gezond en smaakvol alternatief',
    'products.poultry.item5': 'Kipgehakt: Licht en smaakvol, voor gezonde variaties',
    'products.poultry.item6': 'Gevulde Kip: Onze specialiteit, een feest op tafel',
    'products.poultry.cta': 'Bestel Online',
    'products.bbq.title': 'BBQ & Grill: Perfecte Smaak',
    'products.bbq.subtitle': 'Speciaal geselecteerd en gemarineerd voor de perfecte barbecue-ervaring. Van klassieke spare ribs tot huisgemaakte burgers.',
    'products.bbq.item1': 'Spare Ribs: Malse spare ribs, langzaam gegaard en perfect gemarineerd',
    'products.bbq.item2': 'Hamburgers (huisgemaakt): Onze legendarische, huisgemaakte hamburgers. Puur vlees, pure smaak',
    'products.bbq.item3': 'Gemarineerde Spiesjes: Vers gemaakte spiesjes met verschillende soorten vlees',
    'products.bbq.item4': 'BBQ Pakketten: Complete pakketten voor elke BBQ, van intiem tot groots feest',
    'products.bbq.item5': 'Braadworsten: Perfect voor op de grill, vol van smaak',
    'products.bbq.item6': 'Chipolata: Kleine, kruidig gekruide worstjes ideaal voor de barbecue',
    'products.bbq.cta': 'Bestel Online',
    'products.specialties.title': 'Onze Specialiteiten: Smaakmakers van Slager John',
    'products.specialties.subtitle': 'Ontdek de unieke creaties en ambachtelijke meesterwerken die Slager John zo bijzonder maken. Perfect voor uw BBQ, feest of gewoon een smaakvol moment.',
    'products.specialties.homemade.title': 'Huisgemaakte Producten',
    'products.specialties.homemade.item1': 'Gehaktballen (speciaal recept): Onze befaamde gehaktballen, bereid met een geheim familierecept',
    'products.specialties.homemade.item2': 'Verse worst (verschillende smaken): Dagelijks vers gedraaide worsten, van klassiek tot kruidig',
    'products.specialties.homemade.item3': 'Kruidenboter: Huisgemaakte kruidenboter, de perfecte aanvulling voor elk gerecht',
    'products.specialties.homemade.item4': 'Marinades: Onze unieke, vers bereide marinades die elk stuk vlees transformeren',
    'products.specialties.bbq.title': 'BBQ & Grill',
    'products.specialties.bbq.item1': 'BBQ Pakketten: Complete pakketten voor elke BBQ, van intiem tot groots feest',
    'products.specialties.bbq.item2': 'Gemarineerde Spiesjes: Vers gemaakte spiesjes met verschillende soorten vlees',
    'products.specialties.bbq.item3': 'Hamburgers (huisgemaakt): Onze legendarische, huisgemaakte hamburgers. Puur vlees, pure smaak',
    'products.specialties.bbq.item4': 'Spare Ribs: Malse spare ribs, langzaam gegaard en perfect gemarineerd',
    'products.specialties.cta': 'Bestel Online',
    'products.cta.title': 'Klaar om te Bestellen?',
    'products.cta.subtitle': 'Bekijk ons volledige assortiment, bestel eenvoudig online en laat de ambachtelijke kwaliteit van Slager John bij u thuis bezorgen.',
    'products.cta.button': 'Bestel Online',
    
    // Order Page
    'order.title': 'Bestel Online',
    'order.subtitle': 'Plaats uw bestelling en haal deze af in onze winkel',
    'order.step1.title': 'Selecteer Producten',
    'order.product.label': 'Product',
    'order.product.placeholder': 'Selecteer een product',
    'order.quantity.label': 'Aantal',
    'order.unit.kg': 'kg',
    'order.unit.pieces': 'stuks',
    'order.addProduct': '+ Voeg Product Toe',
    'order.nextStep': 'Volgende Stap',
    'order.step2.title': 'Kies Afhaaltijd',
    'order.pickupDate.label': 'Afhaaldatum',
    'order.pickupDate.placeholder': 'Selecteer datum',
    'order.pickupTime.label': 'Afhaaltijd',
    'order.pickupTime.placeholder': 'Selecteer tijd',
    'order.back': 'Terug',
    'order.step3.title': 'Contactgegevens',
    'order.name.label': 'Naam *',
    'order.phone.label': 'Telefoonnummer *',
    'order.email.label': 'Email *',
    'order.notes.label': 'Opmerkingen (optioneel)',
    'order.notes.placeholder': 'Speciale wensen of opmerkingen...',
    'order.placeOrder': 'Bestelling Plaatsen',
    'order.delivery.title': 'Levering aan huis',
    'order.delivery.intro': 'Zin in onze heerlijke producten, maar geen tijd om te komen winkelen? Geen zorgen — wij brengen het rechtstreeks bij jou thuis!',
    'order.delivery.minimum': 'Minimumbestelling: €50',
    'order.delivery.tier1.free': 'Gratis levering binnen een straal van 10 km',
    'order.delivery.tier1.paid': 'Buiten 10 km — €1 per km',
    'order.delivery.minimum100': 'Bestelling vanaf €100',
    'order.delivery.tier2.free': 'Gratis levering binnen een straal van 20 km',
    'order.delivery.tier2.paid': 'Buiten 20 km — €1 per km',
    'order.delivery.schedule': 'Levering van maandag tot en met zaterdag vanaf 18:00 uur',
    'order.delivery.phone': 'Bestel nu via:',
    'order.delivery.address': 'Bruggestraat 146A, Zwevezele 8750, België',
    'order.delivery.tagline': 'Verse producten, met liefde bij jou thuis geleverd!',
    
    // Contact Page
    'contact.title': 'Contact',
    'contact.subtitle': 'Kom langs in onze winkel of neem contact met ons op',
    'contact.address.title': 'Adres',
    'contact.address.street': 'Bruggestraat 146A',
    'contact.address.city': 'Zwevezele 8750',
    'contact.address.country': 'België',
    'contact.phone.title': 'Telefoon',
    'contact.email.title': 'Email',
    'contact.hours.title': 'Openingsuren',
    'contact.hours.mon': 'Maandag: 13:00 - 18:00',
    'contact.hours.tue': 'Dinsdag: 08:00 - 18:00',
    'contact.hours.wed': 'Woensdag: 08:00 - 13:00',
    'contact.hours.thu': 'Donderdag: 08:00 - 18:00',
    'contact.hours.fri': 'Vrijdag: 08:00 - 18:00',
    'contact.hours.sat': 'Zaterdag: 08:00 - 18:00',
    'contact.hours.sun': 'Zondag: 08:00 - 13:00',
    'contact.cta.title': 'Vragen of Speciale Wensen?',
    'contact.cta.desc': 'Bel ons gerust of kom langs in de winkel. We helpen u graag verder met advies, speciale bestellingen of vragen over bereiding.',
    'contact.form.consent': 'Ik ga akkoord met de verwerking van mijn persoonsgegevens volgens het',
    'contact.form.privacyNotice': 'Uw persoonlijke gegevens worden verwerkt volgens ons',
    
    // Footer
    'footer.contact': 'Contact',
    'footer.quickLinks': 'Snelmenu',
    'footer.hours': 'Openingsuren',
    'footer.hours.day.mon': 'Maandag',
    'footer.hours.day.tue': 'Dinsdag',
    'footer.hours.day.wed': 'Woensdag',
    'footer.hours.day.thu': 'Donderdag',
    'footer.hours.day.fri': 'Vrijdag',
    'footer.hours.day.sat': 'Zaterdag',
    'footer.hours.day.sun': 'Zondag',
    'footer.hours.time.mon': '13:00 - 18:00',
    'footer.hours.time.tue': '08:00 - 18:00',
    'footer.hours.time.wed': '08:00 - 13:00',
    'footer.hours.time.thu': '08:00 - 18:00',
    'footer.hours.time.fri': '08:00 - 18:00',
    'footer.hours.time.sat': '08:00 - 18:00',
    'footer.hours.time.sun': '08:00 - 13:00',
    'footer.about.title': 'Slagerij John',
    'footer.about.desc': 'Uw vertrouwde slager voor vers vlees en huisgemaakte specialiteiten. Kwaliteit en service staan bij ons centraal.',
    'footer.social': 'Volg ons',
    'footer.rights': 'Alle rechten voorbehouden.',
    'footer.privacy': 'Privacybeleid',
    'footer.terms': 'Algemene Voorwaarden',
    'footer.cookies': 'Cookie instellingen',
    'footer.credit': 'Website gemaakt door Gabi Muresan',
    'footer.status.open': 'Nu Open',
    'footer.status.closed': 'Gesloten',
    
    // Privacy Policy Page
    'privacy.title': 'Privacybeleid',
    'privacy.subtitle': 'Hoe wij uw persoonlijke gegevens verzamelen en gebruiken',
    'privacy.updated': 'Laatst bijgewerkt',
    'privacy.intro': 'Bij Slagerij John respecteren we uw privacy en zijn we toegewijd aan het beschermen van uw persoonlijke gegevens. Dit privacybeleid legt uit hoe we uw informatie verzamelen, gebruiken en beschermen conform de Algemene Verordening Gegevensbescherming (AVG) en de Belgische wetgeving.',
    'privacy.controller.title': 'Verwerkingsverantwoordelijke',
    'privacy.controller.name': 'Bedrijfsnaam: [Te verstrekken door eigenaar]',
    'privacy.controller.vat': 'BTW-nummer: [Te verstrekken door eigenaar]',
    'privacy.controller.kbo': 'KBO-nummer: [Te verstrekken door eigenaar]',
    'privacy.controller.address': 'Adres: Bruggestraat 146A, 8750 Zwevezele, België',
    'privacy.controller.contact': 'Contact: contact@slagerij-john.be | +32 466 18 64 57',
    'privacy.collection.title': 'Welke Gegevens Verzamelen Wij',
    'privacy.collection.desc': 'We verzamelen alleen de gegevens die noodzakelijk zijn om onze diensten te leveren:',
    'privacy.collection.item1': 'Naam en contactgegevens wanneer u een bestelling plaatst',
    'privacy.collection.item2': 'E-mailadres voor orderbevestigingen en communicatie',
    'privacy.collection.item3': 'Telefoonnummer voor orderupdates',
    'privacy.collection.item4': 'Bestelgeschiedenis wanneer u een account aanmaakt',
    'privacy.collection.item5': 'Cookies en analysegegevens via Google Analytics (met uw toestemming)',
    'privacy.legal.title': 'Rechtsgrondslag voor Verwerking',
    'privacy.legal.desc': 'Wij verwerken uw gegevens op basis van:',
    'privacy.legal.item1': 'Uitvoering van overeenkomst - voor het verwerken van bestellingen',
    'privacy.legal.item2': 'Toestemming - voor marketingcommunicatie en cookies',
    'privacy.legal.item3': 'Wettelijke verplichting - voor boekhoudkundige en fiscale doeleinden',
    'privacy.legal.item4': 'Gerechtvaardigd belang - voor het verbeteren van onze diensten',
    'privacy.usage.title': 'Hoe Wij Uw Gegevens Gebruiken',
    'privacy.usage.desc': 'Uw gegevens worden uitsluitend gebruikt voor:',
    'privacy.usage.item1': 'Het verwerken en afhandelen van uw bestellingen',
    'privacy.usage.item2': 'Communicatie over uw bestellingen',
    'privacy.usage.item3': 'Het verbeteren van onze diensten',
    'privacy.usage.item4': 'Het voldoen aan wettelijke verplichtingen',
    'privacy.retention.title': 'Bewaartermijnen',
    'privacy.retention.desc': 'Wij bewaren uw gegevens niet langer dan noodzakelijk:',
    'privacy.retention.item1': 'Bestelgegevens: 7 jaar (wettelijke verplichting voor boekhoudkundige doeleinden)',
    'privacy.retention.item2': 'Accountgegevens: Tot u uw account verwijdert',
    'privacy.retention.item3': 'Analytische cookies: Maximaal 2 jaar',
    'privacy.retention.item4': 'Contactformulieren: 1 jaar na ontvangst',
    'privacy.thirdparty.title': 'Delen met Derden',
    'privacy.thirdparty.desc': 'Wij delen uw gegevens alleen met de volgende vertrouwde diensten:',
    'privacy.thirdparty.item1': 'Google Analytics - voor websitestatistieken (geanonimiseerd)',
    'privacy.thirdparty.item2': 'Resend - voor e-mailcommunicatie',
    'privacy.thirdparty.item3': 'WhatsApp - voor ordernotificaties (alleen telefoonnummer)',
    'privacy.thirdparty.note': 'Uw gegevens worden nooit verkocht aan derden voor marketingdoeleinden.',
    'privacy.protection.title': 'Gegevensbescherming',
    'privacy.protection.desc': 'We nemen passende technische en organisatorische maatregelen om uw gegevens te beschermen tegen ongeautoriseerde toegang, verlies of misbruik. Uw gegevens worden veilig opgeslagen met encryptie en regelmatige beveiligingsupdates.',
    'privacy.rights.title': 'Uw Rechten',
    'privacy.rights.desc': 'Onder de AVG heeft u het recht om:',
    'privacy.rights.item1': 'Toegang te krijgen tot uw persoonlijke gegevens',
    'privacy.rights.item2': 'Correctie van onjuiste gegevens te vragen',
    'privacy.rights.item3': 'Verwijdering van uw gegevens te verzoeken ("recht op vergetelheid")',
    'privacy.rights.item4': 'Bezwaar te maken tegen gegevensverwerking',
    'privacy.rights.item5': 'Beperking van verwerking te verzoeken',
    'privacy.rights.item6': 'Overdraagbaarheid van uw gegevens te verzoeken',
    'privacy.rights.item7': 'Een klacht in te dienen bij de Gegevensbeschermingsautoriteit',
    'privacy.complaint.title': 'Klacht Indienen',
    'privacy.complaint.desc': 'Als u niet tevreden bent met hoe wij uw gegevens verwerken, heeft u het recht een klacht in te dienen bij:',
    'privacy.complaint.authority': 'Gegevensbeschermingsautoriteit (GBA)',
    'privacy.complaint.address': 'Drukpersstraat 35, 1000 Brussel, België',
    'privacy.complaint.website': 'Website: https://www.gegevensbeschermingsautoriteit.be',
    'privacy.complaint.email': 'Email: contact@apd-gba.be',
    'privacy.contact.title': 'Contact',
    'privacy.contact.desc': 'Voor vragen over dit privacybeleid of om uw rechten uit te oefenen, neem contact met ons op via:',
    
    // Terms & Conditions Page
    'terms.title': 'Algemene Voorwaarden',
    'terms.subtitle': 'Voorwaarden voor het gebruik van onze diensten',
    'terms.updated': 'Laatst bijgewerkt',
    'terms.intro': 'Deze algemene voorwaarden zijn van toepassing op alle bestellingen en diensten die door Slagerij John worden geleverd. Door gebruik te maken van onze diensten gaat u akkoord met deze voorwaarden.',
    'terms.orders.title': 'Bestellingen',
    'terms.orders.item1': 'Alle bestellingen zijn onder voorbehoud van beschikbaarheid',
    'terms.orders.item2': 'We behouden ons het recht voor om bestellingen te weigeren',
    'terms.orders.item3': 'Bestellingen moeten binnen 24 uur van tevoren worden geplaatst',
    'terms.orders.item4': 'U ontvangt een bevestiging van uw bestelling per e-mail',
    'terms.payment.title': 'Betaling',
    'terms.payment.item1': 'Betaling geschiedt bij afhaling in de winkel',
    'terms.payment.item2': 'We accepteren contant geld en bankkaarten',
    'terms.payment.item3': 'Prijzen zijn inclusief BTW',
    'terms.payment.item4': 'Prijzen kunnen zonder voorafgaande kennisgeving worden gewijzigd',
    'terms.pickup.title': 'Afhaling',
    'terms.pickup.item1': 'Bestellingen moeten worden afgehaald op de afgesproken datum en tijd',
    'terms.pickup.item2': 'Als u niet op tijd kunt afhalen, neem dan contact met ons op',
    'terms.pickup.item3': 'Niet-afgehaalde bestellingen kunnen worden geannuleerd na 24 uur',
    'terms.pickup.item4': 'U dient een geldig identificatiebewijs te tonen bij afhaling',
    'terms.quality.title': 'Productkwaliteit',
    'terms.quality.desc': 'We garanderen de hoogste kwaliteit van onze producten. Als u niet tevreden bent met een product, neem dan onmiddellijk contact met ons op. We streven ernaar om eventuele problemen snel en eerlijk op te lossen.',
    'terms.liability.title': 'Aansprakelijkheid',
    'terms.liability.desc': 'Slagerij John is niet aansprakelijk voor schade die voortvloeit uit onjuist gebruik of bewaring van producten na afhaling. Volg altijd de bewaarinstructies en consumeer producten vóór de vermelde houdbaarheidsdatum.',
    'terms.contact.title': 'Contact',
    'terms.contact.desc': 'Voor vragen over deze algemene voorwaarden, neem contact met ons op:',
    
    // Auth
    'auth.title': 'Authenticatie',
    'auth.description': 'Log in op je account of maak een nieuw account',
    'auth.welcome': 'Welkom',
    'auth.subtitle': 'Log in of maak een account aan',
    'auth.login': 'Inloggen',
    'auth.signup': 'Registreren',
    'auth.email': 'Email',
    'auth.password': 'Wachtwoord',
    'auth.confirmPassword': 'Bevestig wachtwoord',
    'auth.name': 'Naam',
    'auth.loading': 'Laden...',
    'auth.logout': 'Uitloggen',
    'auth.forgotPassword': 'Wachtwoord vergeten?',
    'auth.resetPassword': 'Reset Wachtwoord',
    'auth.resetPasswordDesc': 'Voer je email in om een wachtwoord reset link te ontvangen',
    'auth.sendResetLink': 'Verstuur Reset Link',
    'auth.backToLogin': 'Terug naar inloggen',
    'auth.resetEmailSent': 'Reset email verstuurd! Controleer je inbox.',
    
    // My Account Page
    'account.title': 'Mijn Account',
    'account.loading': 'Laden...',
    'account.tabs.profile': 'Profiel',
    'account.tabs.orders': 'Bestellingen',
    'account.tabs.settings': 'Instellingen',
    'account.profile.title': 'Profielinformatie',
    'account.profile.description': 'Bekijk en wijzig je accountgegevens',
    'account.profile.email': 'Email',
    'account.profile.emailNote': 'E-mailadres kan niet worden gewijzigd',
    'account.profile.fullName': 'Volledige Naam',
    'account.profile.fullNamePlaceholder': 'Voer je volledige naam in',
    'account.profile.memberSince': 'Lid sinds',
    'account.profile.update': 'Profiel Bijwerken',
    'account.profile.updating': 'Bijwerken...',
    'account.orders.title': 'Bestellingshistorie',
    'account.orders.description': 'Bekijk al je eerdere en huidige bestellingen',
    'account.orders.loading': 'Bestellingen laden...',
    'account.orders.noOrders': 'Nog geen bestellingen',
    'account.orders.noOrdersText': 'Je hebt nog geen bestellingen geplaatst',
    'account.orders.placeFirst': 'Plaats Je Eerste Bestelling',
    'account.orders.orderDate': 'Besteldatum',
    'account.orders.pickupDate': 'Ophaaldatum',
    'account.orders.pickupTime': 'Ophaaltijd',
    'account.orders.status': 'Status',
    'account.orders.items': 'Items',
    'account.settings.title': 'Accountinstellingen',
    'account.settings.description': 'Beheer je accountvoorkeuren',
    'account.settings.security': 'Accountbeveiliging',
    'account.settings.securityText': 'Om je wachtwoord te wijzigen of beveiligingsinstellingen bij te werken, neem contact op met de ondersteuning.',
    'account.settings.notifications': 'Meldingen',
    'account.settings.notificationsText': 'Je ontvangt e-mailmeldingen over updates van je bestelling.',
    'account.settings.danger': 'Gevarenzone',
    'account.settings.dangerText': 'Om je account te verwijderen, neem contact met ons op via',
    
    // Testimonials
    'testimonials.title': 'Wat Onze Klanten Zeggen',
    'testimonials.rating': 'Gebaseerd op 11 Google recensies',
    'testimonials.viewAll': 'Bekijk alle recensies op Google Maps',
    
    // Home - Christmas Menu
    'home.christmas.title': 'Menu Kerst Nieuwjaar',
    'home.christmas.period': 'November - December',
    'home.christmas.info': 'Voor meer info verwelkomen we u graag in onze winkel!',
    'home.christmas.downloading': 'Downloaden...',
    'home.christmas.download': 'Download PDF Menu',
    
    // Order - Products List
    'order.products.steak': 'Biefstuk',
    'order.products.roast': 'Rosbief',
    'order.products.beefMince': 'Gehakt (rund)',
    'order.products.stew': 'Stoofvlees',
    'order.products.porkTenderloin': 'Varkenshaas',
    'order.products.chops': 'Koteletten',
    'order.products.porkMince': 'Gehakt (varken)',
    'order.products.sausage': 'Braadworst',
    'order.products.wholeChicken': 'Hele kip',
    'order.products.chickenBreast': 'Kipfilet',
    'order.products.chickenThighs': 'Kippendijen',
    'order.products.homemadeSausage': 'Huisgemaakte worst',
    'order.products.meatballs': 'Gehaktballen',
    'order.products.bbqPackage': 'BBQ pakket',
    'order.products.colliPork1': 'Colli varken 1 (€45)',
    'order.products.colliPork2': 'Colli varken 2 (€55)',
    'order.products.colliChicken': 'Colli kip (€50)',
    'order.products.colliMixed': 'Colli kip-varken (€60)',
    'order.products.colliBBQ': 'BBQ Colli (€55)',
    'order.products.colliJohn': 'Colli John (€100)',
    
    // Order - Steps
    'order.steps.products': 'Producten',
    'order.steps.pickup': 'Afhalen',
    'order.steps.contact': 'Contactgegevens',
    'order.steps.confirm': 'Bevestiging',
    
    // Order - Form
    'order.form.product': 'Product',
    'order.form.selectProduct': 'Selecteer een product',
    'order.form.quantity': 'Aantal',
    'order.form.unit': 'Eenheid',
    'order.form.addItem': '+ Voeg Product Toe',
    'order.form.continue': 'Volgende',
    'order.form.back': 'Terug',
    'order.form.submit': 'Bestelling Plaatsen',
    'order.form.submitting': 'Bezig met versturen...',
    'order.form.pickupDate': 'Afhaaldatum',
    'order.form.selectDate': 'Selecteer datum',
    'order.form.pickupTime': 'Afhaaltijd',
    'order.form.selectTime': 'Selecteer tijd',
    'order.form.name': 'Naam',
    'order.form.namePlaceholder': 'Uw naam',
    'order.form.phone': 'Telefoonnummer',
    'order.form.email': 'E-mailadres',
    'order.form.notes': 'Opmerkingen',
    'order.form.notesPlaceholder': 'Speciale wensen of opmerkingen...',
    'order.form.consent': 'Ik ga akkoord met de verwerking van mijn persoonsgegevens volgens het',
    'order.form.privacyNotice': 'Uw persoonlijke gegevens worden verwerkt volgens ons privacybeleid. U heeft recht op toegang, correctie of verwijdering van uw gegevens.',
    
    // Order - Other
    'order.total': 'Totaal',
    'order.loading': 'Producten laden...',
    'order.seo.title': 'Bestel Online',
    'order.seo.description': 'Bestel uw verse producten online bij Slagerij John',
    'order.error.title': 'Fout',
    'order.error.description': 'Er is iets misgegaan bij het plaatsen van uw bestelling',
    'order.error.loadProducts': 'Kan producten niet laden',
    'order.success.title': 'Bestelling Succesvol Geplaatst!',
    'order.success.description': 'Uw bestelling is succesvol geplaatst! We verwachten u op de afgesproken datum en tijd.',
    'order.success.orderTotal': 'Totaalbedrag van uw bestelling',
    'order.success.sendWhatsApp': 'Bevestiging via WhatsApp',
    'order.success.backToHome': 'Terug naar Home',
    
    // Order - Validation
    'order.validation.selectProduct': 'Selecteer een product',
    'order.validation.enterQuantity': 'Vul een hoeveelheid in',
    'order.validation.selectUnit': 'Selecteer een eenheid',
    'order.validation.addProduct': 'Voeg minimaal één product toe',
    'order.validation.selectDate': 'Selecteer een afhaaldatum',
    'order.validation.selectTime': 'Selecteer een afhaaltijd',
    'order.validation.nameMin': 'Naam moet minimaal 2 karakters zijn',
    'order.validation.nameMax': 'Naam mag maximaal 100 karakters zijn',
    'order.validation.phoneMin': 'Telefoonnummer moet minimaal 10 cijfers zijn',
    'order.validation.phoneMax': 'Telefoonnummer mag maximaal 20 cijfers zijn',
    'order.validation.phoneFormat': 'Ongeldig telefoonnummer formaat',
    'order.validation.emailInvalid': 'Ongeldig e-mailadres',
    'order.validation.emailMax': 'E-mailadres mag maximaal 255 karakters zijn',
    'order.validation.notesMax': 'Opmerkingen mogen maximaal 1000 karakters zijn',
    'order.validation.quantityInvalid': 'Aantal moet tussen 0.1 en 1000 zijn',
    
    // Packages Page
    'packages.title': 'Onze Colli\'s',
    'packages.subtitle': 'Voordelige vleespakketten voor elke gelegenheid',
    'packages.featured': 'Aanbevolen',
    'packages.orderOnly': 'Enkel op bestelling!',
    'packages.orderNow': 'Bestel Nu',
    'packages.pork1.title': 'Colli varken 1',
    'packages.pork2.title': 'Colli varken 2',
    'packages.chicken.title': 'Colli kip',
    'packages.mixed.title': 'Colli kip-varken',
    'packages.bbq.title': 'BBQ Colli',
    'packages.john.title': 'Colli John',
    
    // Admin Dashboard
    'admin.title': 'Admin Dashboard',
    'admin.subtitle': 'Beheer bestellingen en klantenverzoeken',
    'admin.tabs.orders': 'Bestellingen',
    'admin.tabs.settings': 'Instellingen',
    'admin.stats.totalOrders': 'Totaal Bestellingen',
    'admin.stats.pending': 'In afwachting',
    'admin.stats.confirmed': 'Bevestigd',
    'admin.stats.ready': 'Klaar',
    'admin.stats.completed': 'Voltooid',
    'admin.orders.title': 'Bestellingen',
    'admin.orders.description': 'Bekijk en beheer klantbestellingen',
    'admin.orders.filterPlaceholder': 'Filter op status',
    'admin.orders.all': 'Alle Bestellingen',
    'admin.orders.pending': 'In afwachting',
    'admin.orders.confirmed': 'Bevestigd',
    'admin.orders.ready': 'Klaar',
    'admin.orders.completed': 'Voltooid',
    'admin.orders.cancelled': 'Geannuleerd',
    'admin.orders.noOrders': 'Geen bestellingen gevonden',
    'admin.orders.more': 'meer',
    'admin.orders.view': 'Bekijk',
    'admin.table.customer': 'Klant',
    'admin.table.items': 'Items',
    'admin.table.total': 'Totaal',
    'admin.table.pickup': 'Afhalen',
    'admin.table.status': 'Status',
    'admin.table.created': 'Aangemaakt',
    'admin.table.actions': 'Acties',
    'admin.orderDetails.title': 'Bestelgegevens',
    'admin.orderDetails.orderId': 'Bestelling',
    'admin.orderDetails.customerInfo': 'Klantinformatie',
    'admin.orderDetails.name': 'Naam:',
    'admin.orderDetails.orderItems': 'Bestelitems',
    'admin.orderDetails.pickupDetails': 'Afhaalgegevens',
    'admin.orderDetails.notes': 'Notities',
    'admin.orderDetails.orderStatus': 'Bestelstatus',
    'admin.orderDetails.readyForPickup': 'Klaar voor Afhaling',
    'admin.orderDetails.sendWhatsApp': 'Stuur WhatsApp Update',
    'admin.orderDetails.printOrder': 'Print Bestelling',
    'admin.settings.templatesTitle': 'WhatsApp Berichtsjablonen',
    'admin.settings.templatesDescription': 'Pas de WhatsApp-berichten aan die naar klanten worden gestuurd voor verschillende bestelstatussen. Gebruik placeholders: {customer_name}, {pickup_date}, {pickup_time}',
    'admin.settings.statusLabel': 'Status',
    'admin.settings.saveTemplate': 'Sjabloon Opslaan',
    'admin.whatsapp.title': 'WhatsApp Bericht Versturen',
    'admin.whatsapp.customizeMessage': 'Pas je bericht aan voor',
    'admin.whatsapp.cancel': 'Annuleren',
    'admin.whatsapp.send': 'Verstuur WhatsApp',
    'admin.toast.newOrder': 'Nieuwe bestelling ontvangen!',
    'admin.toast.statusUpdated': 'Bestelstatus succesvol bijgewerkt',
    'admin.toast.loadFailed': 'Bestellingen laden mislukt',
    'admin.toast.templateUpdated': 'Sjabloon succesvol bijgewerkt',
    'admin.toast.templateFailed': 'Sjabloon bijwerken mislukt',
    'admin.toast.popupBlocked': 'Sta popups toe om bestellingen af te drukken',
    'admin.toast.statusUpdateFailed': 'Bestelstatus bijwerken mislukt',
    'admin.print.orderDetails': 'Bestelgegevens',
    'admin.print.orderInfo': 'Bestelinformatie',
    'admin.print.orderId': 'Bestelling ID:',
    'admin.print.orderDate': 'Besteldatum:',
    'admin.print.status': 'Status:',
    'admin.print.customerInfo': 'Klantinformatie',
    'admin.print.name': 'Naam:',
    'admin.print.phone': 'Telefoon:',
    'admin.print.email': 'E-mail:',
    'admin.print.orderItems': 'Bestelitems',
    'admin.print.product': 'Product',
    'admin.print.quantity': 'Hoeveelheid',
    'admin.print.pickupDetails': 'Afhaalgegevens',
    'admin.print.pickupDate': 'Afhaaldatum:',
    'admin.print.pickupTime': 'Afhaaltijd:',
    'admin.print.notes': 'Notities',
  },
  ro: {
    // Navigation
    'nav.home': 'Acasă',
    'nav.about': 'Despre Noi',
    'nav.products': 'Produse',
    'nav.catering': 'Catering',
    'nav.order': 'Comandă Online',
    'nav.contact': 'Contact',
    
    // Home Page
    'home.hero.title': 'Măcelarul Dvs. de Calitate în Zwevezele',
    'home.hero.subtitle': 'Meșteșug tradițional\ncu servicii moderne',
    'home.hero.cta': 'Comandă Acum Online',
    'home.features.online.title': 'Comandă Online',
    'home.features.online.desc': 'Comandă ușor online și ridică când îți convine',
    'home.features.quality.title': 'Calitate Premium',
    'home.features.quality.desc': 'Numai cea mai bună carne de la furnizori locali de încredere',
    'home.features.fresh.title': 'Preparare Proaspătă',
    'home.features.fresh.desc': 'Pregătit zilnic proaspăt după rețete tradiționale',
    'home.specials.title': 'Oferte Săptămâna Aceasta',
    'home.specials.promo.title': 'Promo 21 & 22 Noiembrie',
    'home.specials.promo.offer1': 'Cumpărături de minim €30 → Primiți gratis 200 gr Préparé van de Chef',
    'home.specials.promo.offer2': 'Cumpărături de minim €50 → Primiți gratis 500 gr de carne tocată',
    'home.specials.order': 'Comandă Acum',
    'home.cta.title': 'Gata să Comenzi?',
    'home.cta.subtitle': 'Descoperă sortimentul nostru complet și comandă astăzi pentru ridicare',
    'home.cta.orderBtn': 'Comandă Online',
    'home.cta.productsBtn': 'Vezi Produsele',
    
    // About Page
    'about.title': 'Despre Măcelăria John',
    'about.subtitle': 'Cea mai nouă achiziție culinară din Zwevezele',
    'about.tagline': 'Descoperă adevăratul gust al cărnii proaspete! În măcelăria noastră, vei găsi doar carne proaspătă, preparate de casa și specialități făcute cu grijă și pasiune. Facem totul cu dragoste, astfel încât să te poți bucura de o aromă autentică în fiecare zi.',
    'about.story.title': 'Povestea Noastră',
    'about.story.p1': 'Bun venit la Măcelăria John, cea mai nouă achiziție culinară din Zwevezele! Pe Bruggestraat 146A, unde odinioară erau brutăriile Choc-O-Fee și Geert, Ion (John) Nistor (36) și soția sa Georgiana (31) și-au îndeplinit visul deschizând propria măcelărie.',
    'about.story.p2': '"De fapt mă numesc Ion, dar toată lumea mă cheamă John," explică măcelarul. "Ion este versiunea românească a numelui și când am venit în Belgia am început să fiu numit John. Numele a rămas. Chiar și soția mea mă cheamă așa!"',
    'about.values.experience.title': 'Experiență & Pasiune',
    'about.values.experience.desc': 'La vârsta de 16 ani, John și-a început cariera în România, unde a dobândit experiență în măcelării și abatoare.',
    'about.values.culture.title': 'Două Culturi',
    'about.values.culture.desc': 'Un amestec unic de specialități belgiene și românești, reprezentat simbolic de figurile noastre cu baloane în ambele culori naționale.',
    'about.values.local.title': 'Conexiune Locală',
    'about.values.local.desc': 'Acasă în Zwevezele de 8 ani, unde familia cu trei copii locuiește pe Laurierstraat și este complet integrată.',
    'about.specialties.title': 'Specialitățile Noastre',
    'about.specialties.intro': 'În vitrina noastră veți găsi o gamă largă de:',
    'about.specialties.item1': 'Mezeluri și charcuterie belgiene clasice',
    'about.specialties.item2': 'Mâncăruri preparate tradițional precum tocană și vol-au-vent',
    'about.specialties.item3': 'Specialități românești precum \'Mici\' (rulouri de carne tocată de vită condimentată)',
    'about.specialties.item4': 'Sandvișuri proaspete',
    'about.specialties.item5': 'Cârnați casnici din carne tocată de porc și vită',
    'about.team.title': 'Echipa din Spatele Măcelăriei John',
    'about.team.names': 'Georgiana Nistor & Ion (John) Nistor',
    'about.team.role': 'Proprietari',
    'about.team.desc': 'Ion (John) și Georgiana sunt gata să vă ajute cu sfaturi, cerințe speciale sau pur și simplu o discuție. Cu pasiunea lor pentru carne de calitate și servicii personalizate, împart cu plăcere cunoștințele despre cele mai bune metode de preparare și rețete. Vino să ne cunoști!',
    'about.gallery.title': 'Măcelăria Noastră',
    
    // Catering Page
    'catering.title': 'Catering',
    'catering.subtitle': 'Experiența Autentică a Grătarului, direct la evenimentul tău',
    'catering.p1': 'Fie că organizați o petrecere intimă cu prietenii sau o mare sărbătoare de cartier, echipa noastră vă transformă evenimentul într-un răsfăț culinar. Noi ne ocupăm de tot ce ține de stația de grătar, astfel încât dumneavoastră să aveți timp pentru invitați.',
    'catering.p2': 'Pachetul nostru include:\n\nMeniu complet: O selecție variată de aperitive și preparate la grătar, gătite pe loc la unitățile noastre mobile profesionale.\n\nBăuturi: Sortimente diverse pentru a completa masa.',
    'catering.p3': 'Logistică inclusă: Asigurăm tacâmurile și farfuriile necesare.',
    'catering.p4': 'Flexibilitate: Oferim servicii complete la locație (gătit și servire la grătar) sau opțiunea de preluare a mâncării. Dumneavoastră alegeți, noi ne ocupăm de foc!',
    'catering.gallery.title': 'Serviciul Nostru de Catering',
    
    // Products Page
    'products.title': 'Produsele Noastre',
    'products.hero.title': 'Produsele Noastre',
    'products.hero.subtitle': 'Descoperiți sortimentul nostru extins și artizanal de carne de cea mai înaltă calitate, pregătită proaspăt zilnic pentru dvs.',
    'products.beef.title': 'Carne de Vită: Pasiune pentru Calitate',
    'products.beef.subtitle': 'Descoperiți carnea noastră de vită atent selectată, cunoscută pentru frageditatea și gustul său bogat. Perfectă pentru orice ocazie, de la o masă rapidă la o cină festivă.',
    'products.beef.item1': 'Friptură: Suculentă și fragedă, de la friptură olandeză clasică la ribeye premium',
    'products.beef.item2': 'Rosbif: Delicios la cuptor, perfect pentru o masă specială',
    'products.beef.item3': 'Carne tocată (Vită): Pură și gustoasă, ideală pentru burgeri, sosuri și tave',
    'products.beef.item4': 'Carne de tocană: Gătită încet pentru un gust profund și memorabil',
    'products.beef.item5': 'Coaste: Perfect pentru BBQ sau o tocană puternică',
    'products.beef.item6': 'File de vită: Cea mai fragedă bucată de carne de vită, pentru o experiență de neuitat',
    'products.beef.cta': 'Bestel Online',
    'products.pork.title': 'Carne de Porc: Artizanal și Gustos',
    'products.pork.subtitle': 'De la preparate tradiționale la delicatese moderne, carnea noastră de porc garantează calitate și gust.',
    'products.pork.item1': 'Mușchi de porc: Fragede și versatile, ideale pentru preparate diverse',
    'products.pork.item2': 'Cotlete: Cotlete suculente pentru grătar sau tigaie',
    'products.pork.item3': 'Carne tocată (Porc): Proaspăt măcinată, perfectă pentru chiftele gustoase sau umpluturi',
    'products.pork.item4': 'Șnicele: Crocante la frigere, o adevărată delicatesă',
    'products.pork.item5': 'Cârnaț de casă: Rețeta noastră proprie, delicios de gustos',
    'products.pork.item6': 'Cârnaț artizanal: Descoperiți cârnații noștri unici, preparați proaspăt zilnic',
    'products.pork.cta': 'Bestel Online',
    'products.poultry.title': 'Pasăre: Proaspătă și Ușoară',
    'products.poultry.subtitle': 'Bucurați-vă de puiul, curcanul și specialitățile noastre de pasăre proaspete zilnic. Ușoare, gustoase și versatile.',
    'products.poultry.item1': 'Pui întreg: Perfect pentru fript sau grătar, plin de gust',
    'products.poultry.item2': 'Piept de pui: Fragede și slab, versatil în orice preparat',
    'products.poultry.item3': 'Pulpe de pui: Mai suculente decât pieptul, ideale pentru tocană sau curry',
    'products.poultry.item4': 'Piept de curcan: O alternativă sănătoasă și gustoasă',
    'products.poultry.item5': 'Carne tocată de pui: Ușoară și gustoasă, pentru variații sănătoase',
    'products.poultry.item6': 'Pui umplut: Specialitatea noastră, o sărbătoare pe masă',
    'products.poultry.cta': 'Bestel Online',
    'products.bbq.title': 'BBQ & Grătar: Gust Perfect',
    'products.bbq.subtitle': 'Special selecționat și marinat pentru experiența perfectă la grătar. De la coaste de porc clasice la burgeri făcuți în casă.',
    'products.bbq.item1': 'Coaste de porc: Coaste fragede, fripte încet și perfect marinate',
    'products.bbq.item2': 'Burgeri (făcuți în casă): Burgerii noștri legendari, făcuți în casă. Carne pură, gust pur',
    'products.bbq.item3': 'Frigărui marinate: Frigărui proaspăt făcuți cu diferite sortimente de carne',
    'products.bbq.item4': 'Pachete BBQ: Pachete complete pentru fiecare BBQ, de la intim la petreceri mari',
    'products.bbq.item5': 'Cârnați de grătar: Perfect pentru grătar, plini de gust',
    'products.bbq.item6': 'Chipolata: Cârnăciori mici, condimentați picant, ideali pentru grătar',
    'products.bbq.cta': 'Bestel Online',
    'products.specialties.title': 'Specialitățile Noastre: Creatorii de Gust Slager John',
    'products.specialties.subtitle': 'Descoperiți creațiile unice și capodoperele artizanale care fac Slager John atât de special. Perfect pentru BBQ-ul dvs., petreceri sau pur și simplu un moment gustos.',
    'products.specialties.homemade.title': 'Produse de Casă',
    'products.specialties.homemade.item1': 'Chiftele (rețetă specială): Chiftelele noastre celebre, preparate cu o rețetă de familie secretă',
    'products.specialties.homemade.item2': 'Cârnaț proaspăt (diverse arome): Cârnaț proaspăt măcinat zilnic, de la clasic la condimentat',
    'products.specialties.homemade.item3': 'Unt cu ierburi: Unt de casă cu ierburi, completarea perfectă pentru orice preparat',
    'products.specialties.homemade.item4': 'Marinade: Marinadele noastre unice, proaspăt preparate, care transformă orice bucată de carne',
    'products.specialties.bbq.title': 'BBQ & Grătar',
    'products.specialties.bbq.item1': 'Pachete BBQ: Pachete complete pentru orice BBQ, de la intim la petrecere mare',
    'products.specialties.bbq.item2': 'Frigărui marinate: Frigărui proaspete cu diverse tipuri de carne',
    'products.specialties.bbq.item3': 'Burgeri (de casă): Burgerii noștri legendari, făcuți în casă. Carne pură, gust pur',
    'products.specialties.bbq.item4': 'Coaste afumate: Coaste fragede, gătite încet și perfect marinate',
    'products.specialties.cta': 'Bestel Online',
    'products.cta.title': 'Gata să Comandați?',
    'products.cta.subtitle': 'Vedeți sortimentul nostru complet, comandați simplu online și lăsați calitatea artizanală a Slager John să vină la dvs. acasă.',
    'products.cta.button': 'Bestel Online',
    
    // Order Page
    'order.title': 'Comandă Online',
    'order.subtitle': 'Plasează comanda și ridică-o din magazinul nostru',
    'order.step1.title': 'Selectează Produse',
    'order.product.label': 'Produs',
    'order.product.placeholder': 'Selectează un produs',
    'order.quantity.label': 'Cantitate',
    'order.unit.kg': 'kg',
    'order.unit.pieces': 'bucăți',
    'order.addProduct': '+ Adaugă Produs',
    'order.nextStep': 'Pasul Următor',
    'order.step2.title': 'Alege Ora de Ridicare',
    'order.pickupDate.label': 'Data ridicării',
    'order.pickupDate.placeholder': 'Selectează data',
    'order.pickupTime.label': 'Ora ridicării',
    'order.pickupTime.placeholder': 'Selectează ora',
    'order.back': 'Înapoi',
    'order.step3.title': 'Date de Contact',
    'order.name.label': 'Nume *',
    'order.phone.label': 'Număr de telefon *',
    'order.email.label': 'Email *',
    'order.notes.label': 'Observații (opțional)',
    'order.notes.placeholder': 'Cerințe speciale sau observații...',
    'order.placeOrder': 'Plasează Comanda',
    'order.delivery.title': 'Livrare la domiciliu',
    'order.delivery.intro': 'Ai poftă de produsele noastre, dar nu ai timp să vii la cumpărături? Nicio grijă — le aducem noi direct la tine acasă!',
    'order.delivery.minimum': 'Comandă minimă: 50 €',
    'order.delivery.tier1.free': 'Livrare GRATUITĂ pe o rază de 10 km',
    'order.delivery.tier1.paid': 'După 10 km — 1 € / km',
    'order.delivery.minimum100': 'Comandă de minim 100 €',
    'order.delivery.tier2.free': 'Livrare GRATUITĂ pe o rază de 20 km',
    'order.delivery.tier2.paid': 'După 20 km — 1 € / km',
    'order.delivery.schedule': 'Livrăm începând cu ora 18:00, de luni pana sambata',
    'order.delivery.phone': 'Sună acum pentru comenzi:',
    'order.delivery.address': 'Bruggestraat 146A, Zwevezele 8750, Belgia',
    'order.delivery.tagline': 'Produse proaspete, livrate cu drag — direct la tine acasă!',
    
    // Contact Page
    'contact.title': 'Contact',
    'contact.subtitle': 'Treci pe la magazinul nostru sau contactează-ne',
    'contact.address.title': 'Adresă',
    'contact.address.street': 'Bruggestraat 146A',
    'contact.address.city': 'Zwevezele 8750',
    'contact.address.country': 'Belgia',
    'contact.phone.title': 'Telefon',
    'contact.email.title': 'Email',
    'contact.hours.title': 'Program',
    'contact.hours.mon': 'Luni: 13:00 - 18:00',
    'contact.hours.tue': 'Marți: 08:00 - 18:00',
    'contact.hours.wed': 'Miercuri: 08:00 - 13:00',
    'contact.hours.thu': 'Joi: 08:00 - 18:00',
    'contact.hours.fri': 'Vineri: 08:00 - 18:00',
    'contact.hours.sat': 'Sâmbătă: 08:00 - 18:00',
    'contact.hours.sun': 'Duminică: 08:00 - 13:00',
    'contact.cta.title': 'Întrebări sau Cerințe Speciale?',
    'contact.cta.desc': 'Sună-ne sau treci pe la magazin. Te ajutăm cu plăcere cu sfaturi, comenzi speciale sau întrebări despre preparare.',
    'contact.form.consent': 'Sunt de acord cu procesarea datelor mele personale conform',
    'contact.form.privacyNotice': 'Datele dumneavoastră personale sunt procesate conform',
    
    // Footer
    'footer.contact': 'Contact',
    'footer.quickLinks': 'Meniu Rapid',
    'footer.hours': 'Program',
    'footer.hours.day.mon': 'Luni',
    'footer.hours.day.tue': 'Marți',
    'footer.hours.day.wed': 'Miercuri',
    'footer.hours.day.thu': 'Joi',
    'footer.hours.day.fri': 'Vineri',
    'footer.hours.day.sat': 'Sâmbătă',
    'footer.hours.day.sun': 'Duminică',
    'footer.hours.time.mon': '13:00 - 18:00',
    'footer.hours.time.tue': '08:00 - 18:00',
    'footer.hours.time.wed': '08:00 - 13:00',
    'footer.hours.time.thu': '08:00 - 18:00',
    'footer.hours.time.fri': '08:00 - 18:00',
    'footer.hours.time.sat': '08:00 - 18:00',
    'footer.hours.time.sun': '08:00 - 13:00',
    'footer.about.title': 'Măcelăria John',
    'footer.about.desc': 'Măcelarul tău de încredere pentru carne proaspătă și specialități casnice. Calitatea și serviciul sunt prioritatea noastră.',
    'footer.social': 'Urmărește-ne',
    'footer.rights': 'Toate drepturile rezervate.',
    'footer.privacy': 'Politica de Confidențialitate',
    'footer.terms': 'Termeni și Condiții',
    'footer.cookies': 'Setări cookie-uri',
    'footer.credit': 'Website creat de Gabi Muresan',
    'footer.status.open': 'Deschis Acum',
    'footer.status.closed': 'Închis',
    
    // Privacy Policy Page
    'privacy.title': 'Politica de Confidențialitate',
    'privacy.subtitle': 'Cum colectăm și utilizăm datele dumneavoastră personale',
    'privacy.updated': 'Ultima actualizare',
    'privacy.intro': 'La Măcelăria John, respectăm confidențialitatea dumneavoastră și ne angajăm să protejăm datele dumneavoastră personale. Această politică de confidențialitate explică modul în care colectăm, utilizăm și protejăm informațiile dumneavoastră conform Regulamentului General privind Protecția Datelor (GDPR) și legislației belgiene.',
    'privacy.controller.title': 'Operator de Date',
    'privacy.controller.name': 'Nume companie: [Va fi furnizat de proprietar]',
    'privacy.controller.vat': 'Număr TVA: [Va fi furnizat de proprietar]',
    'privacy.controller.kbo': 'Număr KBO: [Va fi furnizat de proprietar]',
    'privacy.controller.address': 'Adresă: Bruggestraat 146A, 8750 Zwevezele, Belgia',
    'privacy.controller.contact': 'Contact: contact@slagerij-john.be | +32 466 18 64 57',
    'privacy.collection.title': 'Ce Date Colectăm',
    'privacy.collection.desc': 'Colectăm doar datele necesare pentru a furniza serviciile noastre:',
    'privacy.collection.item1': 'Nume și informații de contact când plasați o comandă',
    'privacy.collection.item2': 'Adresă de email pentru confirmări și comunicări',
    'privacy.collection.item3': 'Număr de telefon pentru actualizări comenzi',
    'privacy.collection.item4': 'Istoric comenzi când creați un cont',
    'privacy.collection.item5': 'Cookie-uri și date analitice prin Google Analytics (cu consimțământul dumneavoastră)',
    'privacy.legal.title': 'Bază Legală pentru Procesare',
    'privacy.legal.desc': 'Procesăm datele dumneavoastră pe baza:',
    'privacy.legal.item1': 'Executarea contractului - pentru procesarea comenzilor',
    'privacy.legal.item2': 'Consimțământ - pentru comunicări marketing și cookie-uri',
    'privacy.legal.item3': 'Obligație legală - pentru scopuri contabile și fiscale',
    'privacy.legal.item4': 'Interes legitim - pentru îmbunătățirea serviciilor noastre',
    'privacy.usage.title': 'Cum Utilizăm Datele Dumneavoastră',
    'privacy.usage.desc': 'Datele dumneavoastră sunt folosite exclusiv pentru:',
    'privacy.usage.item1': 'Procesarea și îndeplinirea comenzilor',
    'privacy.usage.item2': 'Comunicarea despre comenzile dumneavoastră',
    'privacy.usage.item3': 'Îmbunătățirea serviciilor noastre',
    'privacy.usage.item4': 'Respectarea obligațiilor legale',
    'privacy.retention.title': 'Perioade de Păstrare',
    'privacy.retention.desc': 'Păstrăm datele dumneavoastră nu mai mult decât este necesar:',
    'privacy.retention.item1': 'Date comenzi: 7 ani (obligație legală pentru scopuri contabile)',
    'privacy.retention.item2': 'Date cont: Până când ștergeți contul',
    'privacy.retention.item3': 'Cookie-uri analitice: Maxim 2 ani',
    'privacy.retention.item4': 'Formulare contact: 1 an după primire',
    'privacy.thirdparty.title': 'Partajare cu Terți',
    'privacy.thirdparty.desc': 'Partajăm datele dumneavoastră doar cu următoarele servicii de încredere:',
    'privacy.thirdparty.item1': 'Google Analytics - pentru statistici website (anonimizat)',
    'privacy.thirdparty.item2': 'Resend - pentru comunicare email',
    'privacy.thirdparty.item3': 'WhatsApp - pentru notificări comenzi (doar număr telefon)',
    'privacy.thirdparty.note': 'Datele dumneavoastră nu sunt niciodată vândute terților în scopuri marketing.',
    'privacy.protection.title': 'Protecția Datelor',
    'privacy.protection.desc': 'Luăm măsuri tehnice și organizatorice adecvate pentru a proteja datele dumneavoastră împotriva accesului neautorizat, pierderii sau utilizării abuzive. Datele dumneavoastră sunt stocate în siguranță cu criptare și actualizări regulate de securitate.',
    'privacy.rights.title': 'Drepturile Dumneavoastră',
    'privacy.rights.desc': 'Conform GDPR, aveți dreptul de a:',
    'privacy.rights.item1': 'Accesa datele dumneavoastră personale',
    'privacy.rights.item2': 'Solicita corectarea datelor incorecte',
    'privacy.rights.item3': 'Solicita ștergerea datelor dumneavoastră ("dreptul de a fi uitat")',
    'privacy.rights.item4': 'Obiecta la procesarea datelor',
    'privacy.rights.item5': 'Solicita restricționarea procesării',
    'privacy.rights.item6': 'Solicita portabilitatea datelor',
    'privacy.rights.item7': 'Depune o plângere la Autoritatea de Protecție a Datelor',
    'privacy.complaint.title': 'Depunere Plângere',
    'privacy.complaint.desc': 'Dacă nu sunteți mulțumit de modul în care procesăm datele dumneavoastră, aveți dreptul să depuneți o plângere la:',
    'privacy.complaint.authority': 'Autoritatea pentru Protecția Datelor (APD)',
    'privacy.complaint.address': 'Drukpersstraat 35, 1000 Bruxelles, Belgia',
    'privacy.complaint.website': 'Website: https://www.gegevensbeschermingsautoriteit.be',
    'privacy.complaint.email': 'Email: contact@apd-gba.be',
    'privacy.contact.title': 'Contact',
    'privacy.contact.desc': 'Pentru întrebări despre această politică de confidențialitate sau pentru a vă exercita drepturile, contactați-ne la:',
    
    // Terms & Conditions Page
    'terms.title': 'Termeni și Condiții',
    'terms.subtitle': 'Condiții de utilizare a serviciilor noastre',
    'terms.updated': 'Ultima actualizare',
    'terms.intro': 'Acești termeni și condiții se aplică tuturor comenzilor și serviciilor furnizate de Măcelăria John. Prin utilizarea serviciilor noastre, sunteți de acord cu acești termeni.',
    'terms.orders.title': 'Comenzi',
    'terms.orders.item1': 'Toate comenzile sunt sub rezerva disponibilității',
    'terms.orders.item2': 'Ne rezervăm dreptul de a refuza comenzi',
    'terms.orders.item3': 'Comenzile trebuie plasate cu 24 de ore în avans',
    'terms.orders.item4': 'Veți primi o confirmare a comenzii prin email',
    'terms.payment.title': 'Plată',
    'terms.payment.item1': 'Plata se face la ridicare în magazin',
    'terms.payment.item2': 'Acceptăm numerar și carduri bancare',
    'terms.payment.item3': 'Prețurile includ TVA',
    'terms.payment.item4': 'Prețurile pot fi modificate fără notificare prealabilă',
    'terms.pickup.title': 'Ridicare',
    'terms.pickup.item1': 'Comenzile trebuie ridicate la data și ora convenite',
    'terms.pickup.item2': 'Dacă nu puteți ridica la timp, contactați-ne',
    'terms.pickup.item3': 'Comenzile neridicate pot fi anulate după 24 de ore',
    'terms.pickup.item4': 'Trebuie să prezentați o identificare validă la ridicare',
    'terms.quality.title': 'Calitatea Produselor',
    'terms.quality.desc': 'Garantăm cea mai înaltă calitate a produselor noastre. Dacă nu sunteți mulțumit de un produs, contactați-ne imediat. Ne străduim să rezolvăm orice problemă rapid și corect.',
    'terms.liability.title': 'Răspundere',
    'terms.liability.desc': 'Măcelăria John nu este responsabilă pentru daunele rezultate din utilizarea sau depozitarea incorectă a produselor după ridicare. Urmați întotdeauna instrucțiunile de depozitare și consumați produsele înainte de data de expirare indicată.',
    'terms.contact.title': 'Contact',
    'terms.contact.desc': 'Pentru întrebări despre acești termeni și condiții, contactați-ne:',
    
    // Auth
    'auth.title': 'Autentificare',
    'auth.description': 'Conectați-vă la contul dvs. sau creați un cont nou',
    'auth.welcome': 'Bun venit',
    'auth.subtitle': 'Conectați-vă sau creați un cont',
    'auth.login': 'Conectare',
    'auth.signup': 'Înregistrare',
    'auth.email': 'Email',
    'auth.password': 'Parolă',
    'auth.confirmPassword': 'Confirmă parola',
    'auth.name': 'Nume',
    'auth.loading': 'Se încarcă...',
    'auth.logout': 'Deconectare',
    'auth.forgotPassword': 'Ai uitat parola?',
    'auth.resetPassword': 'Resetează Parola',
    'auth.resetPasswordDesc': 'Introdu email-ul tău pentru a primi un link de resetare a parolei',
    'auth.sendResetLink': 'Trimite Link de Resetare',
    'auth.backToLogin': 'Înapoi la autentificare',
    'auth.resetEmailSent': 'Email de resetare trimis! Verifică-ți inbox-ul.',
    
    // My Account Page
    'account.title': 'Contul Meu',
    'account.loading': 'Se încarcă...',
    'account.tabs.profile': 'Profil',
    'account.tabs.orders': 'Comenzi',
    'account.tabs.settings': 'Setări',
    'account.profile.title': 'Informații Profil',
    'account.profile.description': 'Vezi și actualizează detaliile contului tău',
    'account.profile.email': 'Email',
    'account.profile.emailNote': 'Adresa de email nu poate fi schimbată',
    'account.profile.fullName': 'Nume Complet',
    'account.profile.fullNamePlaceholder': 'Introduceți numele complet',
    'account.profile.memberSince': 'Membru din',
    'account.profile.update': 'Actualizare Profil',
    'account.profile.updating': 'Se actualizează...',
    'account.orders.title': 'Istoric Comenzi',
    'account.orders.description': 'Vezi toate comenzile tale trecute și actuale',
    'account.orders.loading': 'Se încarcă comenzile...',
    'account.orders.noOrders': 'Nicio comandă încă',
    'account.orders.noOrdersText': 'Nu ai plasat încă nicio comandă',
    'account.orders.placeFirst': 'Plasează Prima Ta Comandă',
    'account.orders.orderDate': 'Data Comenzii',
    'account.orders.pickupDate': 'Data Ridicării',
    'account.orders.pickupTime': 'Ora Ridicării',
    'account.orders.status': 'Status',
    'account.orders.items': 'Articole',
    'account.settings.title': 'Setări Cont',
    'account.settings.description': 'Gestionează preferințele contului tău',
    'account.settings.security': 'Securitate Cont',
    'account.settings.securityText': 'Pentru a schimba parola sau a actualiza setările de securitate, te rugăm să contactezi suportul.',
    'account.settings.notifications': 'Notificări',
    'account.settings.notificationsText': 'Vei primi notificări pe email despre actualizările statusului comenzii.',
    'account.settings.danger': 'Zonă Periculoasă',
    'account.settings.dangerText': 'Pentru a șterge contul, te rugăm să ne contactezi la',
    
    // Testimonials
    'testimonials.title': 'Ce Spun Clienții Noștri',
    'testimonials.rating': 'Bazat pe 11 recenzii Google',
    'testimonials.viewAll': 'Vezi toate recenziile pe Google Maps',
    
    // Home - Christmas Menu
    'home.christmas.title': 'Meniu Crăciun Anul Nou',
    'home.christmas.period': 'Noiembrie - Decembrie',
    'home.christmas.info': 'Pentru mai multe informații, te așteptăm cu drag în magazinul nostru!',
    'home.christmas.downloading': 'Se descarcă...',
    'home.christmas.download': 'Descarcă Meniul PDF',
    
    // Order - Products List
    'order.products.steak': 'Mușchi',
    'order.products.roast': 'Rosbif',
    'order.products.beefMince': 'Carne tocată (vită)',
    'order.products.stew': 'Carne de tocană',
    'order.products.porkTenderloin': 'Mușchi de porc',
    'order.products.chops': 'Cotlete',
    'order.products.porkMince': 'Carne tocată (porc)',
    'order.products.sausage': 'Cârnați de grătar',
    'order.products.wholeChicken': 'Pui întreg',
    'order.products.chickenBreast': 'Piept de pui',
    'order.products.chickenThighs': 'Pulpe de pui',
    'order.products.homemadeSausage': 'Cârnați casnici',
    'order.products.meatballs': 'Chiftele',
    'order.products.bbqPackage': 'Pachet BBQ',
    'order.products.colliPork1': 'Colli porc 1 (€45)',
    'order.products.colliPork2': 'Colli porc 2 (€55)',
    'order.products.colliChicken': 'Colli pui (€50)',
    'order.products.colliMixed': 'Colli pui-porc (€60)',
    'order.products.colliBBQ': 'Colli BBQ (€55)',
    'order.products.colliJohn': 'Colli John (€100)',
    
    // Order - Steps
    'order.steps.products': 'Produse',
    'order.steps.pickup': 'Ridicare',
    'order.steps.contact': 'Contact',
    'order.steps.confirm': 'Confirmare',
    
    // Order - Form
    'order.form.product': 'Produs',
    'order.form.selectProduct': 'Selectează un produs',
    'order.form.quantity': 'Cantitate',
    'order.form.unit': 'Unitate',
    'order.form.addItem': '+ Adaugă Produs',
    'order.form.continue': 'Continuă',
    'order.form.back': 'Înapoi',
    'order.form.submit': 'Trimite Comanda',
    'order.form.submitting': 'Se trimite...',
    'order.form.pickupDate': 'Data ridicării',
    'order.form.selectDate': 'Selectează data',
    'order.form.pickupTime': 'Ora ridicării',
    'order.form.selectTime': 'Selectează ora',
    'order.form.name': 'Nume',
    'order.form.namePlaceholder': 'Numele dumneavoastră',
    'order.form.phone': 'Telefon',
    'order.form.email': 'Email',
    'order.form.notes': 'Observații',
    'order.form.notesPlaceholder': 'Dorințe speciale sau observații...',
    'order.form.consent': 'Sunt de acord cu procesarea datelor mele personale conform',
    'order.form.privacyNotice': 'Datele dumneavoastră personale sunt procesate conform politicii noastre de confidențialitate. Aveți dreptul de acces, corectare sau ștergere a datelor.',
    
    // Order - Other
    'order.total': 'Total',
    'order.loading': 'Se încarcă produsele...',
    'order.seo.title': 'Comandă Online',
    'order.seo.description': 'Comandați produsele dumneavoastră proaspete online de la Slagerij John',
    'order.error.title': 'Eroare',
    'order.error.description': 'A apărut o problemă la plasarea comenzii',
    'order.error.loadProducts': 'Nu se pot încărca produsele',
    'order.success.title': 'Comandă Plasată cu Succes!',
    'order.success.description': 'Comanda dumneavoastră a fost plasată cu succes! Vă așteptăm la data și ora convenite.',
    'order.success.orderTotal': 'Suma totală a comenzii',
    'order.success.sendWhatsApp': 'Confirmare prin WhatsApp',
    'order.success.backToHome': 'Înapoi la Pagina Principală',
    
    // Order - Validation
    'order.validation.selectProduct': 'Selectează un produs',
    'order.validation.enterQuantity': 'Introdu cantitatea',
    'order.validation.selectUnit': 'Selectează unitatea',
    'order.validation.addProduct': 'Adaugă cel puțin un produs',
    'order.validation.selectDate': 'Selectează o dată de ridicare',
    'order.validation.selectTime': 'Selectează o oră de ridicare',
    'order.validation.nameMin': 'Numele trebuie să aibă cel puțin 2 caractere',
    'order.validation.nameMax': 'Numele poate avea maxim 100 de caractere',
    'order.validation.phoneMin': 'Numărul de telefon trebuie să aibă cel puțin 10 cifre',
    'order.validation.phoneMax': 'Numărul de telefon poate avea maxim 20 de cifre',
    'order.validation.phoneFormat': 'Format număr de telefon invalid',
    'order.validation.emailInvalid': 'Adresa de email invalidă',
    'order.validation.emailMax': 'Adresa de email poate avea maxim 255 de caractere',
    'order.validation.notesMax': 'Observațiile pot avea maxim 1000 de caractere',
    'order.validation.quantityInvalid': 'Cantitatea trebuie să fie între 0.1 și 1000',
    
    // Packages Page
    'packages.title': 'Pachetele Noastre',
    'packages.subtitle': 'Pachete avantajoase de carne pentru orice ocazie',
    'packages.featured': 'Recomandat',
    'packages.orderOnly': 'Doar la comandă!',
    'packages.orderNow': 'Comandă Acum',
    'packages.pork1.title': 'Colli porc 1',
    'packages.pork2.title': 'Colli porc 2',
    'packages.chicken.title': 'Colli pui',
    'packages.mixed.title': 'Colli pui-porc',
    'packages.bbq.title': 'Colli BBQ',
    'packages.john.title': 'Colli John',
    
    // Admin Dashboard
    'admin.title': 'Panou de Administrare',
    'admin.subtitle': 'Gestionează comenzile și cererile clienților',
    'admin.tabs.orders': 'Comenzi',
    'admin.tabs.settings': 'Setări',
    'admin.stats.totalOrders': 'Total Comenzi',
    'admin.stats.pending': 'În așteptare',
    'admin.stats.confirmed': 'Confirmat',
    'admin.stats.ready': 'Gata',
    'admin.stats.completed': 'Finalizat',
    'admin.orders.title': 'Comenzi',
    'admin.orders.description': 'Vizualizează și gestionează comenzile clienților',
    'admin.orders.filterPlaceholder': 'Filtrează după status',
    'admin.orders.all': 'Toate Comenzile',
    'admin.orders.pending': 'În așteptare',
    'admin.orders.confirmed': 'Confirmat',
    'admin.orders.ready': 'Gata',
    'admin.orders.completed': 'Finalizat',
    'admin.orders.cancelled': 'Anulat',
    'admin.orders.noOrders': 'Nu s-au găsit comenzi',
    'admin.orders.more': 'mai mult',
    'admin.orders.view': 'Vezi',
    'admin.table.customer': 'Client',
    'admin.table.items': 'Articole',
    'admin.table.total': 'Total',
    'admin.table.pickup': 'Ridicare',
    'admin.table.status': 'Status',
    'admin.table.created': 'Creat',
    'admin.table.actions': 'Acțiuni',
    'admin.orderDetails.title': 'Detalii Comandă',
    'admin.orderDetails.orderId': 'Comandă',
    'admin.orderDetails.customerInfo': 'Informații Client',
    'admin.orderDetails.name': 'Nume:',
    'admin.orderDetails.orderItems': 'Articole Comandă',
    'admin.orderDetails.pickupDetails': 'Detalii Ridicare',
    'admin.orderDetails.notes': 'Note',
    'admin.orderDetails.orderStatus': 'Status Comandă',
    'admin.orderDetails.readyForPickup': 'Gata pentru Ridicare',
    'admin.orderDetails.sendWhatsApp': 'Trimite Update WhatsApp',
    'admin.orderDetails.printOrder': 'Printează Comanda',
    'admin.settings.templatesTitle': 'Șabloane Mesaje WhatsApp',
    'admin.settings.templatesDescription': 'Personalizează mesajele WhatsApp trimise clienților pentru diferite statusuri ale comenzilor. Folosește placeholder-uri: {customer_name}, {pickup_date}, {pickup_time}',
    'admin.settings.statusLabel': 'Status',
    'admin.settings.saveTemplate': 'Salvează Șablonul',
    'admin.whatsapp.title': 'Trimite Mesaj WhatsApp',
    'admin.whatsapp.customizeMessage': 'Personalizează mesajul pentru',
    'admin.whatsapp.cancel': 'Anulează',
    'admin.whatsapp.send': 'Trimite WhatsApp',
    'admin.toast.newOrder': 'Comandă nouă primită!',
    'admin.toast.statusUpdated': 'Status comandă actualizat cu succes',
    'admin.toast.loadFailed': 'Încărcarea comenzilor a eșuat',
    'admin.toast.templateUpdated': 'Șablon actualizat cu succes',
    'admin.toast.templateFailed': 'Actualizarea șablonului a eșuat',
    'admin.toast.popupBlocked': 'Permite popup-urile pentru a printa comenzile',
    'admin.toast.statusUpdateFailed': 'Actualizarea statusului comenzii a eșuat',
    'admin.print.orderDetails': 'Detalii Comandă',
    'admin.print.orderInfo': 'Informații Comandă',
    'admin.print.orderId': 'ID Comandă:',
    'admin.print.orderDate': 'Data Comenzii:',
    'admin.print.status': 'Status:',
    'admin.print.customerInfo': 'Informații Client',
    'admin.print.name': 'Nume:',
    'admin.print.phone': 'Telefon:',
    'admin.print.email': 'Email:',
    'admin.print.orderItems': 'Articole Comandă',
    'admin.print.product': 'Produs',
    'admin.print.quantity': 'Cantitate',
    'admin.print.pickupDetails': 'Detalii Ridicare',
    'admin.print.pickupDate': 'Data Ridicării:',
    'admin.print.pickupTime': 'Ora Ridicării:',
    'admin.print.notes': 'Note',
  },
};

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [language, setLanguage] = useState<Language>('nl');

  const handleSetLanguage = (lang: Language) => {
    setLanguage(lang);
    trackLanguageChange(lang);
  };

  const t = (key: string): string => {
    return translations[language][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage: handleSetLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
